### PR TITLE
recaptcha support and JSON patch

### PR DESCRIPTION
**Pull request by kennethrapp**
I was able to get json.rkt to work with some minor edits but a more robust solution may still be necessary. 

Since this is a bit controversial, I'll leave it alone as an example to draw from for JSON operations in general. 

Sorry about all the mess with the html and css edits as well, I was hoping to get the html macros cleaned up for generating the recaptcha html but it didn't work out as planned.

### CODE REVIEW

**Comment by akkartik** [comment]
Not controversial at all! And I agree that a love json example is useful. So keep going!

**Comment by kennethrapp** [comment]
I don't know why the check failed. It works in localhost, though.

**Comment by rocketnia** [comment]
I'm noticing some problems with the library now:

```
arc> (is (fromstring "[]" (read-json)) (fromstring "false" (read-json)))
t
arc> (tostring:write-json:fromstring "true" (read-json))
"\"t\""
```

It looks like these add onto some problems the library already had:

```
arc> (is (fromstring "[]" (read-json)) (fromstring "null" (read-json)))
t
arc> (tostring:write-json:fromstring "null" (read-json))
"nil"
```

Another issue: For `(tostring:write-json:fromstring "false" (read-json))`, the library now returns `"nil"` instead of `"true"`, but neither way seems correct.

Anyway, I'm burying the lede with digressions here. The one problem I wanted to mention was a new _design_ flaw: This library is now associating the two Racket values `()` and `'nil` (which are usually treated as the same value in Arc) with three distinct JSON values: `[]`, `null`, and now `false`.

It's pretty easy to use Racket booleans from Arc using techniques like `(isnt #f x)`. However, if you don't like bothering with Racket booleans for everyday Arc purposes, then perhaps using the Arc symbols `'true`, `'false`, and `null` would let you represent JSON booleans and null values in a fairly Arc-natural way without confusing them with lists. Then you could use techniques like `(isnt 'false x)` to convert these JSON-style booleans to Arc-style booleans. This is just about as inconvenient as using the Racket booleans though, so I'm not sure what would be best.

**Comment by hjek** [comment]
> I was able to get json.rkt to work with some minor edits but a more robust solution may still be necessary.

Looks like there's a [JSON library](https://docs.racket-lang.org/json/index.html) in Racket base, and it may be more up-to-date and robust than `json.rkt`. Haven't looked at this, but it may be easier (if that is the goal) to have a wrapper for the Racket JSON lib than dealing with a full separate Arc/Racket implementation of it.

It's at least worth a look.

**Comment by rocketnia** [comment]
I checked out why the tests were breaking. The fixes turned out to be pretty small: https://github.com/arclanguage/anarki/commit/02b238f8612c08c4427646c68b645a134aa8949f and https://github.com/arclanguage/anarki/commit/7f7b51e7afcac985f6f8772c5164a348a86f564a.

The use of `body` as a macro name surprises me, since `body` is already commonly used as a local variable in Arc for macro bodies. I find my macro bodies often compile into higher-order procedure callbacks, so I name my callbacks `body` a lot, for consistency with the macro version. In this case, two calls I was making to the callbacks looked like `(body)`, which was now being compiled as a macro call. But thanks to this, I noticed `fnform` in srv.arc already uses the variable name `bodyfn` for its callback, so I renamed my variables to `bodyfn`, and there's no problem now.

Meanwhile, I want to mention that I deleted a few of your comments and stylistic changes in the first commit. I think the code aligns better with its surroundings this way, and the comments didn't seem to apply to the fixed version of the code, but I won't mind if you revert any of these changes.

**Comment by kennethrapp** [comment]
Sorry... in hindsight the macro issue should have been obvious. Thanks for catching it.

**Pull request merged**
