### PR TITLE
Dev prompt/app editor

### PR DESCRIPTION
**Pull request by kennethrapp**
Combined prompt and repl into one page, and updated prompt to (hopefully) better serve as a general purpose plugin and code editor. 

Apps can be assigned to and removed from the hooks table, although I couldn't get this to do anything useful or affect News in any way... the hook name is the same as the app name.

### CODE REVIEW

**Comment by kennethrapp** [comment]
It looks like the failure has something to do with building the help pages? I didn't touch any of that.

**Comment by rocketnia** [comment]
It's not that building the help pages failed. It's that building the help pages involves running the tests, so I didn't bother having the Travis CI script run both scripts. So any test failure will say "./arc.sh -n build-web-help.arc" failed now. I suppose that's confusing, huh?

The failure is:

```
open-input-file: cannot open input file
  path: /home/travis/build/arclanguage/anarki/appeditor.arc
  system error: No such file or directory; errno=2
```

Looks like your appeditor.arc file is located at apps/news/appeditor.arc, but in news.arc you wrote `(require "appeditor.arc")` instead of (require "apps/news/appeditor.arc"), so it's trying to load it from the root directory.

**Comment by kennethrapp** [comment]
(require "apps/news/appeditor.arc") doesn't work when I run run-news.cmd, though, it tries to find the file relative to the news directory.

**Comment by kennethrapp** [comment]
Still messing with this... I don't want to move run-news.cmd outside the news directory because I feel like it should be self-contained, but I still haven't been able to get an include path to work for both news and the tests. 

I feel like the "real" solution should be changing the way include or load works. If (include 'lib/...arc) works from anywhere, as it seems to, it's because that path is special cased, but that path makes it *appear* as if include starts looking for files from the root directory, which would imply that (include 'apps/news/...arc) should also work anywhere, but it doesn't.

So maybe we either need to be able to add more include paths (and so have a list of canonical file paths to include from) or else have include search by default from the root directory, so that includes work the same regardless of where they are.

**Pull request closed without merging**
