### PR TITLE
removed blog and events, integrated editor and repl

### PR DESCRIPTION
**Pull request by kennethrapp**
I commented out the blog and events pages for now, since that doesn't seem to be the default. The editor and repl will now appear in the top menu for logged in admins.

I also moved the includes for news into news itself, since it didn't make sense to me for the script starting news to also be responsible for its dependencies.

### CODE REVIEW

**Comment by akkartik** [comment]
Maybe we should treat blog and events as first-class apps? If so, maybe you could just delete the lines you commented out and move the files out to directly under `apps`/?

Maybe we should try to allow combinations of the apps to coexist simply by loading them?

**Comment by kennethrapp** [comment]
The way the editor is currently built, it seems to require an 'app' be a script that takes a 'run' command without arguments and returns the result only to the admin user... so some refactoring would need to be done to make the blog and events work in the editor. 

But I do think expanding prompt.arc a good idea... I was already planning on shared apps that can be used by multiple admins. Public apps would just be one step beyond that.

**Comment by kennethrapp** [comment]
I tried that and apparently Arc doesn't deal well with including files with relative paths? 
I got the following when trying to include blog and events from within the apps folder:

```
#%app: missing procedure expression;
probably originally () which is an illegal empty application
```

so I'm committing with the includes commented out but the files still in place so maybe you can help debug. There might also be a general issue with not having paths like the path to /lib or /apps set canonically somewhere.

**Comment by akkartik** [comment]
It's a strange error. Do you want to move these files but still include them in `news`?

**Comment by hjek** [comment]
The blog is a sample application by PG:
> [See the sample application in blog.arc for ideas about how to make web apps that do more.](http://old.ycombinator.com/arc/tut.txt)

I modified it a little bit to disallow anyone from editing/deleting other users' posts. The original example app is meant to run on its own, independent from News.

Events is just a simple vent calendar I wrote, and it works ok for what it does, but is missing fairly essential features like recurring events.

**Pull request merged**
