### PR TITLE
add arc.cmd to launch anarki from Windows command prompt

### PR DESCRIPTION
**Pull request by prozion**
Hi! I have made a batch file for Windows that make possible to run anarki in the way I described in http://arclanguage.org/item?id=19961

### CODE REVIEW

**Comment by akkartik** [comment]
Awesome, thanks!

**Comment by akkartik** [comment]
I just gave you commit access to this repo. Let me know if you have any issues committing to it. Thanks again!

**Comment by prozion** [comment]
Ok, thank you! Where can I read about anarki project and its rules in addition to README?

**Comment by akkartik** [comment]
We don't hold much truck with rules :) Just run the tests before every
commit and make sure there are no failures. In fact, if you can report if
the tests pass in Windows, that would be very useful.

**Comment by prozion** [comment]
Well, 3 of 606 failed. I will look into a bit later, what happened.

**Comment by akkartik** [comment]
Thanks! Let me try it as well just in case we have some baseline failures
creeping in.

Could you paste the output of the tests here or on the Forum?

**Comment by akkartik** [comment]
Confirmed that the tests all pass on other platforms.

**Comment by prozion** [comment]
* Two fails related to the logging paths for server,
* One fail in getting 302 response instead of 200 while requesting google.com

My output:
...
Running suite srv.run-request
srv.run-request.empty-request failed: open-output-file: cannot open output file
  path: c:\bin\anarki\www/logs/srv-2016-09-22
  system error: Системе не удается найти указанный путь.; errno=3
srv.run-request.simple-request failed: open-output-file: cannot open output file
  path: c:\bin\anarki\www/logs/news-2016-09-22
  system error: Системе не удается найти указанный путь.; errno=3
...
Running suite web.send-request
web.send-request.ping-google failed: (caar (mkreq 'www.google.com')) should be 'HTTP/1.0 200 OK' but instead was 'HTTP/1.0 302 Found'
...

Russian text means "The system can not find the path specified"

I have rewrited srvdir* definition in srv.arc to pass the first two, but I am not sure it's what needed. Regarding Redirect in http response, it's really interesting to know why it happens, it's not the first time I get redirects on my machine when I expect to get normal 200.

**Comment by akkartik** [comment]
Thanks for the investigation! I think we don't need to fix these for your
situation. Just watch out for new failures past those.

**Pull request merged**
